test_vpn: ../../../gelin/test_vpn.bat

ansible_user: administrateur
ansible_password: rootsan
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: credssp
