#Supprime les fichiers d'installation et notifie de la fin de préparation



- name: Suppression du dossier temp
  win_file:
    path: C:\Windows\Temp\
    state: absent
    
- name: Création du dossier temp
  win_file:
    path: C:\Windows\Temp
    state: directory