- name: SophosCustomerToken
  uri:
    url: https://app.atera.com/api/v3/customvalues/customerfield/{ id_client }}/SophosSrv
    method: GET
    body_format: json
    headers:
      fake-api-key: "7422aade19f94934b0463d7c1964afb6"


- name: SophosMgmtServer
  uri:
    url: https://app.atera.com/api/v3/customvalues/customerfield/{ id_client }}/SophosKey
    method: GET
    body_format: json
    headers:
      fake-api-key: "7422aade19f94934b0463d7c1964afb6"
#- name: SophosMgmtServer
#  shell: 'curl -X GET --header "Accept: text/json" --header "X-API-KEY: 7422aade19f94934b0463d7c1964afb6" "https://app.atera.com/api/v3/customvalues/customerfield/{ id_client }}/SophosKey"'
#  register: sophoskey
#-local-action: shell echo '{{ var_mgmtserver }} > /etc/ansible/roles/atera/files/{{ sophoskey.stdout }}'