#Instlalation des logiciels via chocolatey
  - name: Install Firefox
    win_chocolatey:
        name:
        - firefox
        state: present

  - name: Install Chrome
    win_chocolatey:
        name:
        - googlechrome
        state: present

  - name: Install 7Zip
    win_chocolatey:
        name:
        - 7zip
        state: present

  - name: Install PDF Creator
    win_chocolatey:
        name:
        - pdfcreator
        state: present

  - name: Install VLC
    win_chocolatey:
        name:
        - vlc
        state: present

  - name: Install Greenshot
    win_chocolatey:
        name:
        - greenshot
        state: present

  - name: Install Lenovo Update
    win_chocolatey:
        name:
        - lenovo-thinkvantage-system-update
        state: present