

#Installation mise à jour Windows
- name: Installation mise à jour Windows
  win_updates:
    category_names:
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - Updates
    
    reboot: yes
    reboot_timeout: 600