#- name: Créer dossier config temp
#  win_file:
#    path: c:\Windows\Temp\config\
#    state: directory
#
#- name: Copy vpn pass server to computer
#  win_copy:
#    src: "{{ item }}"
#    dest: C:\Windows\Temp\config\
#  with_items:
#    - pass_xg.txt
#    - pass_sg.txt
#    - grand_access_vpn.ps1
#    - provectio_ssl_vpn_config.ovpn
#    - launch_vpn.bat
#
#
#- name: Modification de droit repertoire Sophos VPN
#  win_shell: c:\windows\temp\config\grand_access_vpn.ps1
#
#- name: Copy pass vpn computer to folder
#  win_copy:
#    src: C:\Windows\Temp\config
#    dest: c:\Program Files (x86)\Sophos\Sophos SSL VPN Client\
#    remote_src: True

- name: Lancement du VPNs
  win_command: openvpn-gui --connect provectio_ssl_vpn_config.ovpn
  args:
    chdir: c:\Program Files (x86)\Sophos\Sophos SSL VPN Client\config

#- name: Integration
#  win_domain_membership:
#      dns_domain_name: gelin.local
#      hostname: mydomainclient
#      domain_admin_user: gelin\administrateur
#      domain_admin_password: rootsan
#      domain_ou_path: "OU=Windows,OU=Servers,DC=gelin,DC=local"
#      state: domain
#    register: domain_state
#
#  - win_reboot:
#    when: domain_state.reboot_required