- name: Récupération du fichier d'installation d'Atera
  win_shell: 'Invoke-WebRequest -Uri "http://support.provect.io/GetAgent/Msi/?customerId={{ customer_id }}&integratorLogin=clement.lerch@provectio.fr" -OutFile C:\Windows\temp\AteraAgent.msi'
  
- name: Install atera
  win_msi:
    path: C:\Windows\Temp\AteraAgent.msi
    state: present