#Instlalation Sophos Antivirus
- name: Copy Sophos installer
  win_copy:
    src: "{{ item }}"
    dest: C:\Windows\Temp\
  with_items:
    - SophosSetup.exe

#sophos CDEA
- name: Install Sophos Antivirus
  win_package:
    path: C:\Windows\Temp\SophosSetup.exe
    product_id: '{85F78DA7-8E8E-49C9-969F-A62D2B43C046}'
    arguments: '--customertoken="{{ sophos_customer_token }}" --mgmtserver="{{ sophos_mgmt_server }}" --products=antivirus --quiet'
    state: present
    