#Instlalation Sophos Antivirus
- name: Copy Sophos installer
  win_copy:
    src: "{{ item }}"
    dest: C:\Windows\Temp\
  with_items:
    - SophosSetup.exe

- name: Install Sophos Antivirus
  win_package:
    path: C:\Windows\Temp\SophosSetup.exe
    product_id: '{85F78DA7-8E8E-49C9-969F-A62D2B43C046}'
    arguments: '--customertoken=4c0bf672-6064-4789-ac9d-e20536dd70b7 --mgmtserver=mcs-cloudstation-eu-central-1.prod.hydra.sophos.com --products=antivirus --quiet'
    state: present